services:
  db:
    image: postgres:15-alpine
    container_name: alex_db
    restart: always
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: alexdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - alex_net

  backend:
    build:
      context: ./backend/express-ts-openai
      dockerfile: Dockerfile
    container_name: alex_app
    restart: always
    command: npm run dev
    volumes:
      - ./backend/express-ts-openai:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    # CAMBIO AQUÍ: Ahora lo busca en la raíz
    env_file:
      - .env 
    depends_on:
      - db
    networks:
      - alex_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: alex_frontend
    restart: always
    ports:
      - "5173:5173"
    # También puedes añadirlo al frontend si necesitas variables ahí
    env_file:
      - .env
    networks:
      - alex_net

networks:
  alex_net:
    driver: bridge

volumes:
  postgres_data:
  