name: Sync to GitLab

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push to GitLab
        run: |
          git remote add gitlab https://${{ secrets.USERNAME }}:${{ secrets.GITLAB_PAT }}@${{ secrets.GITLAB_URL }}
          git push gitlab main --force
