services:
  app:
    build: .
    container_name: alex_app
    restart: always
    # Esta es la ruta correcta según tu explorador de archivos
    command: node src/services/app.js
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: alex_db
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: alexdb